# Generated by Django 4.1.1 on 2022-09-09 20:06

from django.db import migrations, models
import restaurant.utils.models
import restaurant.validators


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=restaurant.utils.models.generate_pdf_file_path, verbose_name='PDF-файл чека'),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=32, validators=[restaurant.validators.ChoicesValidator([('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')])], verbose_name='Статус чека'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=32, validators=[restaurant.validators.ChoicesValidator([('kitchen', 'Kitchen'), ('client', 'Client')])], verbose_name='Тип чека'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=32, validators=[restaurant.validators.ChoicesValidator([('kitchen', 'Kitchen'), ('client', 'Client')])], verbose_name='Тип чека'),
        ),
    ]
