# Generated by Django 4.1.1 on 2022-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('rendered', 'Rendered'), ('printed', 'Printed')], max_length=32, verbose_name='Статус чека'),
        ),
        migrations.AlterField(
            model_name='check',
            name='type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=32, verbose_name='Тип чека'),
        ),
        migrations.AlterField(
            model_name='printer',
            name='check_type',
            field=models.CharField(choices=[('kitchen', 'Kitchen'), ('client', 'Client')], max_length=32, verbose_name='Тип чека'),
        ),
        migrations.AddConstraint(
            model_name='check',
            constraint=models.CheckConstraint(check=models.Q(('type__in', ['kitchen', 'client'])), name='type_has_valid_value'),
        ),
        migrations.AddConstraint(
            model_name='check',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['new', 'rendered', 'printed'])), name='status_has_valid_value'),
        ),
        migrations.AddConstraint(
            model_name='printer',
            constraint=models.CheckConstraint(check=models.Q(('check_type__in', ['kitchen', 'client'])), name='check_type_has_valid_value'),
        ),
    ]
