# Generated by Django 4.1.1 on 2022-09-19 21:02

from django.db import migrations, models
import restaurant.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_check_status_alter_check_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=restaurant.utils.models.generate_pdf_file_path, verbose_name='PDF-файл чека'),
        ),
    ]
